version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
  proxy_redis:
    image: "redis"
    container_name: proxy_redis